name: Terraform Action
description: Create VMs using Terraform
inputs:
  vmCounts:
    description: Number of VMs to be created
    required: false
    default: 3
runs:
  using: docker
  image: Dockerfile
