name: Terraform Action
description: Create VMs using Terraform
inputs:
  vmCounts:
    description: Number of VMs to be created
    required: false
    default: 3
  userName:
    description: user name to log-in to provider
    required: false
    default: 123
  password:
    description:  password to log-in to provider
    required: false
    default: 123
runs:
  using: docker
  image: Dockerfile
