name: Terraform Action
description: Create VMs using Terraform
inputs:
  vmCounts:
    description: Number of VMs to be created
    required: false
    default: 3
  userName:
    description: user name to log-in to provider
    required: true   
  password:
    description:  password to log-in to provider
    required: true
  pat:
    description:  PAT
    required: true
outputs:
   result:
    description:The output for terraform output command
runs:
  using: docker
  image: docker/Dockerfile
 
