on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Terraform Setup'
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './create-vm/docker'
        tf_actions_version: latest
      
      
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'plan' 
        tf_actions_working_dir: './create-vm/docker'
        tf_actions_version: latest
        args: '-var="nutanix-userName=${{ secrets.NUTANIX_USERNAME }}" -var="nutanix-password=${{ secrets.NUTANIX_PASSWORD }}" -var="vm-count=1" -var="vm-name-prefix=Sr4-Perf"'
        
        
    
    
    
