on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
 steps:
  - name: 'Checkout'
    uses: actions/checkout@v2

  - name: 'Terraform Setup'
    uses: hashicorp/setup-terraform@v1
    
   - name: 'Terraform Init'
        run: terraform init
    
    
    
